import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigrations1753021093781 implements MigrationInterface {
    name = 'AutoGeneratedMigrations1753021093781'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "transfer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "senderId" uuid, "receiverId" uuid, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "balance" SET DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_780bd0b359a2b4576b2e3268600" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_6bad5b656535794d899c2a50323" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_6bad5b656535794d899c2a50323"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_780bd0b359a2b4576b2e3268600"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "balance" SET DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE "transfer"`);
    }

}
